In [3]:
# Numpy Revise
import numpy as np

In [4]:
#Dimensions And Shape Of Array

In [9]:
arr = np.array([1 , 2 , 4 ,5 ,56])
print(arr.ndim)
arr.shape

1


(5,)

In [12]:
#Creating An Array Using Inbuilt Functionsd
arr = np.arange(1 , 11)#Start Stop Step
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
arr = np.linspace(0 , 1 , 10)#Start , stop , number of vals
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [18]:
arr = np.logspace(1 , 3 , 3)#10^1 - 10 ^ 3--3 Points#Start Power , ending power , even points

In [24]:
arr = np . zeros((3 , 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
arr = np.zeros((2 , 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
arr = np.ones(7 , )
print(arr)

[1. 1. 1. 1. 1. 1. 1.]


In [30]:
arr = np.full((2 , 4) , 7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]]


In [32]:
#Uninitialised Arrays
arr = np.empty((2 , 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
arr = np.random.rand(2 , 3)
print(arr)


[[0.40917904 0.92813728 0.4948196 ]
 [0.29736364 0.90260434 0.76063429]]


In [36]:
arr = np.random.randn(2 , 3)
print(arr)

[[-0.52877677 -0.27420706 -0.90792226]
 [-2.10722897  0.18975018  1.3726148 ]]


In [38]:
arr = np.random.randint(1 , 101 , size = (3 , 3))
print(arr)

[[56 46 41]
 [24 80 25]
 [21 30 67]]


In [39]:
#Numpy Dtypes And Type Casting

In [41]:
arr = np.array([1 , 2 , 3.1, 4 , 5 ])
print(type(arr))

<class 'numpy.ndarray'>


In [43]:
arr = np.array([1 , 2 ,3 ,4 ,545 , 6])
print(arr.dtype)

int64


In [46]:
#Type Casting
arr = np.array([1 , 2 , 3 , 4 , 5 , 6] , dtype = "float64")
print(arr.dtype)

float64


In [47]:
#astype


In [50]:
arr = np.array([1 , 2 , 3])
arr2 = arr.astype(np.float64)
print(arr2.dtype)
arr3 = arr2.astype(np.float64)
print(arr3.dtype)

float64
float64


In [56]:
#Creating A 2D Array
arr = np.array([[1 , 2 ,  3] , [4 , 5 , 6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.itemsize)
print(arr.dtype)

(2, 3)
6
2
8
int64


In [57]:
#Reshape


In [61]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape((2, 3 ))
print(reshaped)
reshaped2 = reshaped.reshape((3 , 2))
print(reshaped2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [63]:
#Ravel - Any Array Into 1D Array
#Return View

In [68]:
Ravel = reshaped2.ravel()
print((Ravel))
Ravel[0] = 1001
print(reshaped2)

[1001    2    3    4    5    6]
[[1001    2]
 [   3    4]
 [   5    6]]


In [69]:
#Flatten - Turns Into 1D array
#Just A Copy

In [72]:
faltten = Ravel.flatten()
print(faltten)

[1001    2    3    4    5    6]


In [76]:
faltten[1] = 0
print(faltten)
print(Ravel)

[1001    0    3    4    5    6]
[1001    2    3    4    5    6]


In [77]:
#Arithmetic Ops On Arrays

In [82]:
a = np.array([2 , 2 , 2])
b = np.array([2 , 2 , 2])
print(a+b)
print(a - b)
print(a*b)
print(a/b)
print(a//b)

[4 4 4]
[0 0 0]
[4 4 4]
[1. 1. 1.]
[1 1 1]


In [84]:
#Exponential Ops
print(a**b)

[4 4 4]


In [85]:
#Universal Function


In [88]:
arr = np.array([1 , 4 , 9 , 16])
arr2 = np.sqrt(arr)
print(arr2)

[1. 2. 3. 4.]


In [90]:
#e^x
arr = np.exp([1 , 2])
print(arr)

[2.71828183 7.3890561 ]


In [91]:
#Indexing And Slicing

In [95]:
a = [1 , 2 , 4 ,5 ]
print(a[-1 : -4 : -1])
print(a[::2])

[5, 4, 2]
[1, 4]


In [96]:
arr = np.array([1 , 2 , 3 , 4 , 5])
#indexes - 0 , 2, 4
print(arr[::2])

[1 3 5]


In [100]:
matrix = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [ 7 , 8 , 9]])
print(matrix[0:2])
print(matrix[1:3 , 1:3])

[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]


In [104]:
#Fancy Indexing
arr = np.array([10 , 20 , 30 , 40 , 50 , 60])
idx=[0 , 1 , 3]
print(arr[idx])

[10 20 40]


In [105]:
#View vs copy

In [108]:
arr = np.array([1 , 2 , 3 , 4 , 5])
view = arr[1:3]
print(view)
view[0] = 200
print(view)

[2 3]
[200   3]


In [109]:
copy = arr[1:3].copy()
copy[0] = 2
print(copy)
print(arr)

[2 3]
[  1 200   3   4   5]


In [113]:
arr = np.array([[1 , 2] , [ 3  , 4]])
arr2 = arr.transpose()
print(arr2)

[[1 3]
 [2 4]]


In [114]:
#Swap Axes

In [116]:
arr = np.array([[[1 , 2] , [ 3  , 4]]])
print(arr.shape)
swap = np.swapaxes(arr , 0 , 1)
print(swap.shape)

(1, 2, 2)
(2, 1, 2)


In [118]:
#Concatenate
a = np.array([1 , 2 , 3])
b = np.array([1 , 2 , 3])
c = np.concatenate((a , b))
print(c)


[1 2 3 1 2 3]


In [122]:
#Vstack and Hstack
arr1 = np.array([[1 , 2] , [3 , 4]])
arr2 = np.array([[5 , 6] , [7 , 8]])
vstack = np.vstack((arr1 , arr2))
print(vstack)
hstack = np.hstack((arr1 , arr2))
print(hstack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [125]:
#Repeat And Tile
arr = np.array([1 , 2 , 4])
arr2 = np.repeat(arr , 2)
arr3 = np.tile(arr , 2)
print(arr2)
print(arr3)

[1 1 2 2 4 4]
[1 2 4 1 2 4]


In [129]:
arr = np.array([1 , 2 , 3 , 4 ,5 , 6])
mask= (arr>3) & (arr<6)
print(arr[mask])

[4 5]


In [133]:
#Indexing And Slicing In 3d array
arr3d = np.array([[[1 , 2] , [3 , 4] , [5, 6]] , [[1 , 2] , [3 , 4] , [5 , 6]]])
print(arr3d.shape)
print(arr3d[0 , 1 , 1])
#Slicing
#First Row From Both LAyers


(2, 3, 2)
4
