In [1]:
#D-1

In [2]:
import numpy as np

In [3]:
#Data Creation
np.random.seed(42)
marks = np.random.randint(0, 101, size=20)
print(marks)

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]


In [4]:
#Basic Statstics
average_marks = np.mean(marks)
highest_mark = np.max(marks)
lowest_mark = np.min(marks)
print(average_marks)
print(highest_mark)
print(lowest_mark)

53.1
99
1


In [5]:
#Avg Count

mask = marks>average_marks
above_avg_count = np.sum(mask)
print(above_avg_count)




10


In [6]:
#Fail Rule Application
marks_set = np.array(marks)
mask2 = marks<40
marks_set[mask2] = 0
print(marks_set)


[51 92  0 71 60  0 82 86 74 74 87 99  0  0  0 52  0 87  0  0]


In [7]:
#Z - Score Normalization
#Marks Normalization
avg = np.mean(marks)
std = np.std(marks)
normalized_vector = (marks - avg)/std
print(normalized_vector)

[-0.06672587  1.23601731 -1.24237216  0.56875861  0.21924215 -1.05172681
  0.91827507  1.04537197  0.66408128  0.66408128  1.07714619  1.45843688
 -0.95640414 -1.62366284 -1.01995259 -0.03495165 -1.65543707  1.07714619
 -0.7657588  -0.51156501]


In [8]:
# Boolean masking is better because NumPy executes it in optimized C code,
# avoiding slow Python-level loops and per-element overhead.

# With 2,000,000 students, Python loops become extremely slow and memory-inefficient,
# while vectorized NumPy operations still run efficiently at scale.

# Operations like counting, filtering, replacing values, and normalization would be
# very slow in pure Python loops due to repeated interpreter overhead.


In [9]:
#2d arrays


In [10]:
#Data Creation
np.random.seed(42)
scores = np.random.randint(1 , 101 , size = (5 , 30))
print(scores)
print(scores.shape)



[[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
   30  38   2  64  60  21  33  76  58  22  89  49]
 [ 91  59  42  92  60  80  15  62  62  47  62  51  55  64   3  51   7  21
   73  39  18   4  89  60  14   9  90  53   2  84]
 [ 92  60  71  44   8  47  35  78  81  36  50   4   2   6  54   4  54  93
   63  18  90  44  34  74  62 100  14  95  48  15]
 [ 72  78  87  62  40  85  80  82  53  24  26  89  60  41  29  15  45  65
   89  71   9  88   1   8  88  63  11  81   8  35]
 [ 35  33   5  41  28   7  73  72  12  34  33  48  23  62  88  37  99  44
   86  91  35  65  99  47  78   3   1   5  90  14]]
(5, 30)


In [11]:
avg = np.mean(scores , axis = 1)#Per section
highest_marks = np.max(scores , axis = 1)
lowest_marks = np.min(scores , axis = 1)
print(avg)
print(highest_marks)
print(lowest_marks)

[51.86666667 48.63333333 49.2        52.83333333 46.26666667]
[100  92 100  89  99]
[2 2 2 1 1]


In [12]:
#In each section we have to count students which are greater than avg and then store them in a single array
above_avg_marks = scores > avg[:,np.newaxis]
above_avg_count = np.sum(above_avg_marks , axis = 1)
print(above_avg_count)

[17 18 15 17 13]


In [14]:
#Fail Rule 
marks_s = np.array(scores)
mask = scores < 35
marks_s[mask] = 0
print(marks_s)


[[ 52  93   0  72  61   0  83  87  75  75  88 100   0   0   0  53   0  88
    0  38   0  64  60   0   0  76  58   0  89  49]
 [ 91  59  42  92  60  80   0  62  62  47  62  51  55  64   0  51   0   0
   73  39   0   0  89  60   0   0  90  53   0  84]
 [ 92  60  71  44   0  47  35  78  81  36  50   0   0   0  54   0  54  93
   63   0  90  44   0  74  62 100   0  95  48   0]
 [ 72  78  87  62  40  85  80  82  53   0   0  89  60  41   0   0  45  65
   89  71   0  88   0   0  88  63   0  81   0  35]
 [ 35   0   0  41   0   0  73  72   0   0   0  48   0  62  88  37  99  44
   86  91  35  65  99  47  78   0   0   0  90   0]]


In [27]:
#Z - Score Normalisation
avg = np.mean(scores , axis = 1)
avg = avg.reshape((5 , 1))
deviation = np.std(scores , axis = 1)
deviation= deviation.reshape((5 , 1))
z_scores = (scores - avg) / deviation
print(z_scores)

[[ 0.00445954  1.37576944 -1.23306402  0.6733912   0.30547879 -1.03238452
   1.04130361  1.17508994  0.77373095  0.77373095  1.20853652  1.60989552
  -0.93204477 -1.63442301 -0.99893794  0.03790613 -1.66786959  1.20853652
  -0.73136528 -0.46379261 -1.66786959  0.40581854  0.27203221 -1.03238452
  -0.63102553  0.80717753  0.20513904 -0.99893794  1.24198311 -0.0958802 ]
 [ 1.4741556   0.36070999 -0.230808    1.50895078  0.39550516  1.09140867
  -1.17027774  0.46509551  0.46509551 -0.05683212  0.46509551  0.08234858
   0.22152928  0.53468586 -1.58781984  0.08234858 -1.44863914 -0.96150668
   0.84784244 -0.33519352 -1.06589221 -1.55302467  1.40456525  0.39550516
  -1.20507291 -1.37904879  1.43936043  0.15193893 -1.62261502  1.23058937]
 [ 1.41444008  0.35691479  0.7204391  -0.17184786 -1.36156381 -0.07270486
  -0.46927685  0.95177276  1.05091576 -0.43622918  0.02643813 -1.49375447
  -1.5598498  -1.42765914  0.15862879 -1.49375447  0.15862879  1.44748774
   0.45605778 -1.03108716  1.3483447