In [2]:
import numpy as np

In [3]:
marks_data = np.array([
 [101, 78, 85, 90],
 [102, 88, 79, 92],
 [103, 65, 70, 60],
 [104, 90, 95, 93],
 [105, 72, 68, 75]
]
)

In [5]:
#Average Marks Per Student
avg_marks = np.mean(marks_data[:,1:] ,axis = 1)#Avg Marks Per Student
print(avg_marks)
print(avg_marks.shape)

[84.33333333 86.33333333 65.         92.66666667 71.66666667]
(5,)


In [10]:
#Avg Marks Per Subject
avg_sub = np.mean(marks_data[:,1:], axis = 0)#Avg Per Subject
print(avg_sub)
print(avg_sub.shape)

[78.6 79.4 82. ]
(3,)


In [14]:
#Total Marks
total_marks = np.sum(marks_data[:,1:] , axis = 1)
print(total_marks)

[253 259 195 278 215]


In [15]:
#Index Of Topper
index_topper =np.argmax(total_marks)
print(index_topper)


3


In [19]:
#Extracting Roll Number And Topper Info
roll_no = marks_data[index_topper , 0]
print(roll_no)
Marks_topper = total_marks[index_topper]
print(Marks_topper)

104
278


In [21]:
#Subject With Lowest Average
lowest_avg = np.argmin(avg_sub)
subjects = np.array(["Maths", "Physics", "Chemistry"])
print(subjects[lowest_avg])


Maths


In [24]:
#Extracting Marks Coloumns
marks_col = marks_data[:,1:]
print(marks_col , marks_col.shape)

[[78 85 90]
 [88 79 92]
 [65 70 60]
 [90 95 93]
 [72 68 75]] (5, 3)
