In [1]:
#Employee Performance Analytics

In [2]:
import numpy as np

In [6]:
#col[0] = Experience(Years)
#col[1] = Projects Completed
#col[2] = Performance Score
#col[3] = salary(in Thousands)

employees = np.array([
    [2, 5, 65, 40],
    [5, 12, 78, 60],
    [1, 3, 50, 35],
    [8, 20, 90, 85],
    [3, 7, 72, 50],
    [10, 25, 95, 100],
    [4, 9, 68, 55],
    [6, 15, 80, 75],
    [2, 4, 60, 42],
    [7, 18, 88, 82]
])


In [7]:
#BASIC INSPECTION
size = employees.shape
col_mean = np.mean(employees , axis = 0)
col_min = np.min(employees , axis = 0)
col_max = np.max(employees , axis = 0)
print(size)
print(col_mean)
print(col_min)
print(col_max)

(10, 4)
[ 4.8 11.8 74.6 62.4]
[ 1  3 50 35]
[ 10  25  95 100]


In [13]:
#Performance Score Analysis
mask = employees[:,2]>=85
top_performers_count= np.sum(mask)
print(top_performers_count)
#Printing All Rows Of These Employees
print(employees[mask])

3
[[  8  20  90  85]
 [ 10  25  95 100]
 [  7  18  88  82]]


In [22]:
#UnderPAid Performers
salary_mask = employees[:,3]<50
performance_mask  = employees[:,2]>=75
combined = salary_mask & performance_mask
print(employees[combined])
print(np.sum(combined))


[]
0


In [33]:
#Performance-Tier-Classification(New)
Excellent_Performers = employees[:,2]>=90
Good_Performers = employees[:,2]>=75
good_2 = employees[:,2]<90
comb_good = Good_Performers & good_2
avg_performers = employees[:,2]<75
count_excellent = np.sum(Excellent_Performers)
count_good = np.sum(comb_good)
count_avg = np.sum(avg_performers)
print(count_excellent)
print(count_good)
print(count_avg)


2
3
5


In [35]:
#Productivity Index
productivity_index = employees[:,1]/employees[:,0]
print(productivity_index)

[2.5        2.4        3.         2.5        2.33333333 2.5
 2.25       2.5        2.         2.57142857]


In [38]:
#Adding Productivity Index Coloumn To The Original Data Set
p_2 = productivity_index.reshape(-1 , 1)
employees_new = np.hstack((employees , p_2))
print(employees_new)


[[  2.           5.          65.          40.           2.5       ]
 [  5.          12.          78.          60.           2.4       ]
 [  1.           3.          50.          35.           3.        ]
 [  8.          20.          90.          85.           2.5       ]
 [  3.           7.          72.          50.           2.33333333]
 [ 10.          25.          95.         100.           2.5       ]
 [  4.           9.          68.          55.           2.25      ]
 [  6.          15.          80.          75.           2.5       ]
 [  2.           4.          60.          42.           2.        ]
 [  7.          18.          88.          82.           2.57142857]]


In [39]:
#Normalization
e_min = np.min(employees_new , axis = 0)
e_max = np.max(employees_new , axis = 0)
Normalized_arr = (employees_new - e_min)/(e_max - e_min)
print(Normalized_arr)

[[0.11111111 0.09090909 0.33333333 0.07692308 0.5       ]
 [0.44444444 0.40909091 0.62222222 0.38461538 0.4       ]
 [0.         0.         0.         0.         1.        ]
 [0.77777778 0.77272727 0.88888889 0.76923077 0.5       ]
 [0.22222222 0.18181818 0.48888889 0.23076923 0.33333333]
 [1.         1.         1.         1.         0.5       ]
 [0.33333333 0.27272727 0.4        0.30769231 0.25      ]
 [0.55555556 0.54545455 0.66666667 0.61538462 0.5       ]
 [0.11111111 0.04545455 0.22222222 0.10769231 0.        ]
 [0.66666667 0.68181818 0.84444444 0.72307692 0.57142857]]
