In [1]:
#Math In Numpy

In [2]:
import numpy as np

In [3]:
#aggregation functions
arr = np.array([1 , 2 , 3 , 4 , 4 , 5])
su_m = np.sum(arr)
prod = np.prod(arr)
mi_n = np.min(arr)
ma_x = np.max(arr)
idx_min = np.argmin(arr)
idx_max = np.argmax(arr)
med = np.median(arr)

In [4]:
#Power Fuctions

In [7]:
arr = np.array([1 , 2 , 3 , 4 , 4 , 5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr , 3))




[ 1  4  9 16 16 25]
[1.         1.41421356 1.73205081 2.         2.         2.23606798]
[  1   8  27  64  64 125]


In [9]:
#lOG
arr = np.array([1 , 2 , 3 , 4 , 4 , 5])
print(np.log(arr))#log after aNY NUMBER BECOMES BASE
print(np.exp(arr))


[0.         0.69314718 1.09861229 1.38629436 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003  54.59815003
 148.4131591 ]


In [12]:
#Rounding

print(np.round(3.1))
print(np.ceil(3.3))
print(np.trunc(3.14))


3.0
4.0
3.0


In [14]:
arr = np.array([1 , 2 , 3 , 4 , 4 , 5])
print(np.unique(arr))#np.abs--->only positive


[1 2 3 4 5]


In [19]:
#Target--->Slicing Of 2D And 3D Arrays In Numpy
#2d arrays
arr = np.array([[1 , 2 , 3],
                [4 , 5 , 6],
                [7 , 8 , 9]
               ])
#Accesing Specific Element
print(arr[1 , 1])
#Slicing/Extracting A Sub Array
print(arr[1:3 , 1:3])
#Extracting Full Rows And Coloumns
print(arr[0])#Prints 1st row
print(arr[:,1])


5
[[5 6]
 [8 9]]
[1 2 3]
[2 5 8]


In [30]:
arr3d = np.array([ [[1, 2], [3, 4] ], [[5, 6], [7, 8]]])
print(arr3d[0 , 0 , 0 ])
print(arr3d[0])


1
[[1 2]
 [3 4]]


In [36]:
#2x3x2
arr3d = np.array([[[1 , 2] , [3 , 4] , [5 , 6]] , [[7,8],[9,10],[11,12]]])
print(arr3d , arr3d.shape)
#Indexing
print(arr3d[0 , 1 , 1])
#Slicing
print(arr3d[:,0,:])#f - row
print(arr3d[:,:,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [39]:
#2x2x2
arr3d = np.array([[[1 , 2 ] , [3 , 4]] , [[5 , 6] , [7,8]]])
#Subarray Extraction
print(arr3d[0:1 , 0:2 , 0:1])

[[[1]
  [3]]]
