In [8]:
import numpy as np
import time


In [9]:
'''arr = np.array([1 , 4 , 5])
print(arr , type(arr))'''


'arr = np.array([1 , 4 , 5])\nprint(arr , type(arr))'

In [19]:
'''#Efficiency Check b / w numpy and lists
size = 1_00_000
py_list = list(range(size))
start = time.time()
sq_list = [x ** 2 for x in py_list]
end = time.time()
print(f"{end - start}")

#Efficieny Of Numpy
arr = np.array(py_list)
start_t = time.time()
sq_arr = arr**2
end_t = time.time()
print(f"{end_t - start_t}")'''


0.0043566226959228516
0.0002014636993408203


In [24]:
'''#Memory Allocation
import sys
print(f"Python List Size : {sys.getsizeof(py_list) * len(py_list)}")
print(f"Numpy Array Size : {arr.nbytes}")'''

Python List Size : 80005600000
Numpy Array Size : 800000


In [30]:
'''#Creation Of Lists
arr = np.array([1 , 2 , 3 , 4 , 5])
print(arr , type(arr) , arr.dtype , arr.shape)
arr2 = np.array([1 , 2 ,3 , "Anirudh"])
print(arr2 , type(arr2) , arr2.dtype , arr2.shape)
arr3 = np.array([[1 , 2 ,3] , [ 4 ,5 ,6 ] , [ 7 , 8 , 9 ]])
print(arr3 , type(arr3) , arr3.dtype , arr3.shape)'''

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' 'Anirudh'] <class 'numpy.ndarray'> <U21 (4,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [33]:
'''#Creation Of Np arrays using Built In 
arr = np.zeros((3 ,3) , dtype = "int64")#Creates An Array With Zeroes With Dimensions Mentioned
arr2 = np.ones((3 , 3))#Creates An Array With ones With Dimensions Mentioned
arr3 = np.full((3 , 4) , 5)#Creates An Array With Given Val With Dimensions Mentioned
arr4 = np.eye(3)#Identity Matrix
print(f"{arr} \n {arr2} \n {arr3} \n {arr4} \n")'''

'#Creation Of Np arrays using Built In \narr = np.zeros((3 ,3) , dtype = "int64")#Creates An Array With Zeroes With Dimensions Mentioned\narr2 = np.ones((3 , 3))#Creates An Array With ones With Dimensions Mentioned\narr3 = np.full((3 , 4) , 5)#Creates An Array With Given Val With Dimensions Mentioned\narr4 = np.eye(3)#Identity Matrix\nprint(f"{arr} \n {arr2} \n {arr3} \n {arr4} \n")'

In [35]:
'''arr = np.arange( 0 , 11 , 2)#Range Elements
print(arr)
arr2 = np.linspace(1,100,4)#Equal Spaced Elements
print(arr2)'''

[ 0  2  4  6  8 10]
[  1.  34.  67. 100.]


In [38]:
'''#array properties
arr = np.array([[ 0 , 0] , [0 , 0]])
print(arr.shape)#Dimensions - m X n
print(arr.size)#No . of elements
print(arr.dtype)#Data Type
print(arr.ndim)#No . of dimensions
float_arr = arr.astype(np.float64)
print(float_arr.dtype)'''


(2, 2)
4
int64
2
float64


In [41]:
#Reshape Arrays
'''arr = np.array([[1 ,2 ,3] , [4 , 5 , 6]])
reshape = arr.reshape((3 ,2))
print(reshape.shape)
flatten = arr.flatten()
print(flatten)'''

(3, 2)
[1 2 3 4 5 6]


In [45]:
'''#Indexing In Arrays
arr = np.array([[1 , 2 , 3] , [4 ,5 ,6]])
print(arr[0][1])#1d arrays same as list
arr2 = np.array([1 , 2 ,3])
print(arr2[0])'''

2
1


In [46]:
'''#Fancy Indexing 
a = np.array([1 , 2 ,3 ,4])
idx = [0 , 1 ,2 ]
print(a[idx])'''

[1 2 3]


In [69]:
'''#Boolean Index
arr = np.array([1 ,2 ,3 ,4 ,4 ,5])
print(arr[arr>3])
print(arr[arr % 2 == 0])'''

[4 4 5]
[2 4 4]


In [50]:
#Indexing
'''a = np.array([1 , 2 , 3 ,4 ,5 ,6])
print(a[1 : 3])
print(a[1 :])
print(a[: 2])
print(a[:])
print(a[::2])'''

[2 3]
[2 3 4 5 6]
[1 2]
[1 2 3 4 5 6]
[1 3 5]


In [54]:
'''#Copy vs View In Slice
a = [1 , 2 ,3 ,4 ,4]

sub_a = a[1:3]

print(sub_a)

sub_a[0]=2

print(sub_a)

print(a)

arr = np.array([1 ,2 ,3 ,3 ,4,4])

sub_arr = arr[1:3]

print(sub_arr)

sub_arr[0] = 100

print(sub_arr)

print(arr)'''



[2, 3]
[2, 3]
[1, 2, 3, 4, 4]
[2 3]
[100   3]
[  1 100   3   3   4   4]


In [56]:
'''#Simple Analysis B / W List And Numpy Array-->PB 1
lst = [2 ,4 ,6 , 8]
lst_d = [x/2 for x in lst]
arr = np.array(lst)
arr_d = arr / 2
print(lst_d)
print(arr_d)'''

[1.0, 2.0, 3.0, 4.0]
[1. 2. 3. 4.]


In [60]:
'''#Builtin Functions To create Numpy Arrays
arr = np.arange(0 , 10)
arr2 = np.zeros(5 , )
arr3 = np.ones( 5 ,)
print(arr , arr2 , arr3)'''

[0 1 2 3 4 5 6 7 8 9] [0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [62]:
'''arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)'''

(2, 3)
2
6
int64


In [63]:
'''arr = np.array([1, 2, 3, 4, 5, 6])
reshape_arr = arr.reshape((2 , 3))
print(arr)
print(reshape_arr)'''

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [67]:
'''arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print(arr[0][1])
print(arr[1][1])
print(arr[0])
print(arr[:,1])#Coloumn'''



20
50
[10 20 30]
[20 50]


In [70]:
'''arr = np.array([10, 20, 30, 40, 50, 60])
idx1 = [1 , 2 ,3]
idx2= [0 , 2 ,4]
print(arr[idx1])
print(arr[idx2])'''


[20 30 40]
[10 30 50]


In [71]:


'''arr = np.array([1, 2, 3, 4, 5, 6])

# 1. Reshape arr into 2 x 3
reshaped = arr.reshape(2, 3)

# 2. Extract the SECOND column
col = reshaped[:, 1]

# 3. Change all values of that column to 0
col[:] = 0

# 4. Print everything
print("Original arr:", arr)
print("Reshaped:\n", reshaped)
print("Column:", col)'''


Original arr: [1 0 3 4 0 6]
Reshaped:
 [[1 0 3]
 [4 0 6]]
Column: [0 0]
