In [3]:
import numpy as np

'''arr = np.array([2, 4, 6])
print(arr * 2)
print(arr + 2)'''


[ 4  8 12]
[4 6 8]


In [6]:
'''#Creation Of Arrays
arr1 = np.zeros(5 , )#Creates An Array Of Five Zeros
l1 = [1 , 2 , 3 ,4 ,5]
arr2 = np.array(l1)#creates an array from the list
print(arr1 , arr1.dtype)
print(arr2 , arr2.dtype)'''

[0. 0. 0. 0. 0.] float64
[1 2 3 4 5] int64


In [12]:
'''#Shaping And Reshaping
arr1 = np.arange(1 , 13)
print(arr1 , arr1.shape , arr1.ndim)
reshaped_1 = arr1.reshape((3 , 4))
print(reshaped_1 , reshaped_1.shape , reshaped_1.ndim)
reshaped_2 = reshaped_1.reshape((2 , 2 , 3))
print(reshaped_2 , reshaped_2.shape , reshaped_2.ndim)'''

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,) 1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3) 3


In [26]:
#Array And Extractions
'''arr = np.array([[10 , 20 , 30] , [40 , 50 , 60] , [70 , 80 , 90]])
print(arr[1][1])
print(arr[2])
print(arr[:,0])
print(arr[0][1] , arr[0][2] , arr[1][1] , arr[1][2])#Printing
#Extracting A Sub array
print(arr[0 : 2 , 1:3])'''


50
[70 80 90]
[10 40 70]
20 30 50 60
[[20 30]
 [50 60]]


In [37]:
'''arr = np.array([3 , 6 , 9 , 12 , 15 , 18 , 21])
print(arr[1 : 4])#Output 6 ,9 , 12
print(arr[::2])#output 3 , 9 , 15 , 21
print(arr[3 : ])#Output -->Last 4 Elements'''

[ 6  9 12]
[ 3  9 15 21]
[12 15 18 21]


In [38]:


arr = np.array([1, 2, 3, 4, 5])

# Case 1: WITHOUT copy
x = arr[1:4]
x[0] = 99

print("Without copy:")
print("x =", x)
print("arr =", arr)

# Case 2: WITH copy
arr = np.array([1, 2, 3, 4, 5])
y = arr[1:4].copy()
y[0] = 99

print("\nWith copy:")
print("y =", y)
print("arr =", arr)


Without copy:
x = [99  3  4]
arr = [ 1 99  3  4  5]

With copy:
y = [99  3  4]
arr = [1 2 3 4 5]
