In [27]:
#Complex numbers
import numpy as np
'''import numpy as np
a = np.array([3 + 5j])
b = np.array([3 + 5j])
print(a+b)'''

'import numpy as np\na = np.array([3 + 5j])\nb = np.array([3 + 5j])\nprint(a+b)'

In [28]:
'''arr2D = np.array([[1 , 2 , 3] , [ 4 , 5 , 6] , [7 , 8 , 9]])
add = np.sum(arr2D)
print(add)
sum_of_coloumns = np.sum(arr2D , axis = 0)
print(sum_of_coloumns)
sum_rows = np.sum(arr2D , axis = 1)
print(sum_rows)'''

'arr2D = np.array([[1 , 2 , 3] , [ 4 , 5 , 6] , [7 , 8 , 9]])\nadd = np.sum(arr2D)\nprint(add)\nsum_of_coloumns = np.sum(arr2D , axis = 0)\nprint(sum_of_coloumns)\nsum_rows = np.sum(arr2D , axis = 1)\nprint(sum_rows)'

In [29]:
'''import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90,100,110,120]#Extraction Of Element 70
])
print(arr[1 , 2])''

_IncompleteInputError: incomplete input (2446363395.py, line 1)

In [30]:
'''import numpy as np
#Extracting Entire Second Row And 3rd coloumn
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90,100,110,120]
])
print(arr[1])
print(arr[:,2])'''

'import numpy as np\n#Extracting Entire Second Row And 3rd coloumn\narr = np.array([\n    [10, 20, 30, 40],\n    [50, 60, 70, 80],\n    [90,100,110,120]\n])\nprint(arr[1])\nprint(arr[:,2])'

In [31]:
'''import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90,100,110,120]
])
print(arr[0 : 2 , 1 : 3])'''

'import numpy as np\n\narr = np.array([\n    [10, 20, 30, 40],\n    [50, 60, 70, 80],\n    [90,100,110,120]\n])\nprint(arr[0 : 2 , 1 : 3])'

In [32]:
'''import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90,100,110,120]
])
#Extraction of first and last coloumn
print(arr[:,[0 , -1]])'''

'import numpy as np\n\narr = np.array([\n    [10, 20, 30, 40],\n    [50, 60, 70, 80],\n    [90,100,110,120]\n])\n#Extraction of first and last coloumn\nprint(arr[:,[0 , -1]])'

In [33]:
'''data = [5 , 10 , 15 , 20 , 25 , 30]
arr = np.array(data)
reshaped = arr.reshape((2 , 3))
print(reshaped.shape)
print(reshaped.ndim)
print(reshaped.size)'''

'data = [5 , 10 , 15 , 20 , 25 , 30]\narr = np.array(data)\nreshaped = arr.reshape((2 , 3))\nprint(reshaped.shape)\nprint(reshaped.ndim)\nprint(reshaped.size)'

In [34]:
#Pb -- 2
'''arr = np.zeros((3 , 4))
arr2 = np.ones((4 , 3))
arr3 = np.full((2 , 5) , 7)
print(arr , arr2 , arr3)'''

'arr = np.zeros((3 , 4))\narr2 = np.ones((4 , 3))\narr3 = np.full((2 , 5) , 7)\nprint(arr , arr2 , arr3)'

In [35]:
'''arr = np.array([
    [3, 6, 9],
    [12, 15, 18],
    [21, 24, 27]
])
print(arr[1][1])
print(arr[0])
print(arr[:,2])'''

'arr = np.array([\n    [3, 6, 9],\n    [12, 15, 18],\n    [21, 24, 27]\n])\nprint(arr[1][1])\nprint(arr[0])\nprint(arr[:,2])'

In [36]:
'''arr = np.array([
    [3, 6, 9],
    [12, 15, 18],
    [21, 24, 27]
])
print(arr[0 : 2 , 1 : 3])'''

'arr = np.array([\n    [3, 6, 9],\n    [12, 15, 18],\n    [21, 24, 27]\n])\nprint(arr[0 : 2 , 1 : 3])'

In [37]:
'''arr = np.array([10, 20, 30, 40, 50])

# Case 1: WITHOUT copy
sub = arr[1:4]
sub[0] = 999

print("Without copy:")
print("sub =" ,sub)
print("arr =", arr)

# Case 2: WITH copy
arr = np.array([10, 20, 30, 40, 50])
y = arr[1:4].copy()
y[0] = 999

print("\nWith copy:")
print("y =", y)
print("arr =", arr)'''

'arr = np.array([10, 20, 30, 40, 50])\n\n# Case 1: WITHOUT copy\nsub = arr[1:4]\nsub[0] = 999\n\nprint("Without copy:")\nprint("sub =" ,sub)\nprint("arr =", arr)\n\n# Case 2: WITH copy\narr = np.array([10, 20, 30, 40, 50])\ny = arr[1:4].copy()\ny[0] = 999\n\nprint("\nWith copy:")\nprint("y =", y)\nprint("arr =", arr)'

In [38]:
'''#Reshaping of array
arr = np.arange(1 , 13)
reshaped_arr = arr.reshape(3 , 4)
print(reshaped_arr)
print(reshaped_arr[1])
print(reshaped_arr[:,[1 , 2]])'''

'#Reshaping of array\narr = np.arange(1 , 13)\nreshaped_arr = arr.reshape(3 , 4)\nprint(reshaped_arr)\nprint(reshaped_arr[1])\nprint(reshaped_arr[:,[1 , 2]])'

In [26]:
'''arr = np.array([
    [2, 4, 6],
    [8, 10, 12]
])
row_wise_sum = np.sum(arr , axis = 1)
coloumn_wise = np.sum(arr , axis = 0)
mean = np.mean(arr)
print(row_wise_sum)
print(coloumn_wise)
print(mean)'''

[12 30]
[10 14 18]
7.0


In [41]:
'''arr = np.array([1.2 , 2.5 , 3.8 , 4.1])
arr_int = arr.astype(np.int64)
arr_float = arr.astype(np.float32)
print(arr_int , arr_int.dtype)
print(arr_float , arr_float.dtype)'''

[1 2 3 4] int64
[1.2 2.5 3.8 4.1] float32


In [42]:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 95, 94, 96]
])
avg_per_student = np.mean(marks , axis = 1)
avg_per_subject = np.mean(marks , axis = 0)
total_marks = np.sum(marks , axis = 0)
