In [1]:
import numpy as np

In [4]:
arr3D = np.array([[[1 ,2 ] , [3 , 4] , [5 , 6]] , [[7 , 8] , [9 , 10] , [11 , 12]]])
print(arr3D , arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [7]:
#Indexing
print(arr3D[0 , 1 , 1])
print(arr3D[1 , 1 ,0])

4
9


In [9]:
#Slicing
print(arr3D[: , 0 , :])
print(arr3D[: , : , 1])

[[1 2]
 [7 8]]
[[ 2  4  6]
 [ 8 10 12]]


In [11]:
#Vectorization
arr = np.array([1 , 2 , 3 , 4 , 5 , 6])
print(arr**2)
print(arr + 10)

[ 1  4  9 16 25 36]
[11 12 13 14 15 16]


In [12]:
arrx = np.array([1 , 2 , 3 , 4 , 5 , 6])
arry = np.array([1 , 2 , 3 , 4 , 5 , 6])
print(arrx + arry)

[ 2  4  6  8 10 12]


In [13]:
arrz = np.array([1 ,2 ,3 ,4 ,5 ,6])#Broad Casting
arr2 = np.array([[1 ,2 , 3 ,4 ,5 ,6] , [1 , 2 , 3 , 4 ,5 , 6]])
print(arrz+arr2)
print(arrz.shape)
print(arr2.shape)

[[ 2  4  6  8 10 12]
 [ 2  4  6  8 10 12]]
(6,)
(2, 6)


In [15]:
arr = np.array([[1 , 2] , [3 , 4]])
mean = np.mean(arr)
std = np.std(arr)
normalized_arr = (arr-mean)/std
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
