In [4]:
import numpy as np
lst = [1 , 2 , 3 , 4 , 5]
lst_m = []
arr = np.array(lst)
for n in lst:
    lst_m.append(n*2)
arr_m=arr*2
print(arr_m)
print(lst_m)


[ 2  4  6  8 10]
[2, 4, 6, 8, 10]


In [5]:
#Array Creation Using Builtin Methods
arr1 = np.zeros(10)
arr2 = np.arange(1 , 20 , 2)
arr3 = np.linspace(0,1,5 )
print(arr1)
print(arr2)
print(arr3)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1  3  5  7  9 11 13 15 17 19]
[0.   0.25 0.5  0.75 1.  ]


In [6]:
arr4 = np.array([[3, 5, 7],
                [1, 2, 9]])
print(arr4.shape , arr4.ndim , arr4.size , arr4.dtype)



(2, 3) 2 6 int64


In [7]:
arr5 = np.arange(1 , 13)
reshaped = np.reshape(arr5 ,(3 , 4))#Rows x coloumns
reshaped_2 = np.reshape(arr5 , (2 , 2 ,3))#Layers x rows x columns


In [8]:
#INDEXING
arr = np.array([10 , 20 , 30 ,40 , 50 ,60])
#Access 30
print(arr[2])
#change 4 - 99 
arr[3] = 99
print(arr)

30
[10 20 30 99 50 60]


In [9]:
#Indexing
arr = np.array([5, 15, 25, 35, 45])
print(arr[2])
print(arr[-1])
arr[3] = 100
print(arr)

25
45
[  5  15  25 100  45]


In [10]:
#Slicing
arr = np.array([2, 4, 6, 8, 10, 12, 14])
print(arr[1:4])
print(arr[::2])
print(arr[4:7])

[4 6 8]
[ 2  6 10 14]
[10 12 14]


In [11]:
#Copy v/s view
arr = np.array([1 , 2 , 3 , 4 , 5 ,6])
#view
sub = arr[1:4]
sub[0] = 999
print(arr)
#copy
arr2 = np.array([1 , 2 , 3 , 4 , 5 , 6])
y = arr2[1:4].copy()
y[0] = 999
print(arr2)



[  1 999   3   4   5   6]
[1 2 3 4 5 6]


In [12]:
#Data Type Modification++
arr = np.array([1.7, 2.8, 3.9])
it1 = arr.astype(np.int32)
print(it1 , it1.dtype)
ft1 = arr.astype(np.float32)
print(ft1 , ft1.dtype)

[1 2 3] int32
[1.7 2.8 3.9] float32


In [13]:
#numpy 2d array
arr = np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45]])
print(arr[1][1])
print(arr[1])
print(arr[:,2])
print(arr[0:2 , 1:3])


25
[20 25 30]
[15 30 45]
[[10 15]
 [25 30]]


In [14]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
sum_row_wise = np.sum(arr , axis = 1)
coulum_wise = np.sum(arr , axis = 0)
print(sum_row_wise)
print(coulum_wise)

[ 6 15]
[5 7 9]


In [16]:
arr3d = np.arange(1,25)
arr3d.reshape(2 , 3 , 4)
print(arr3d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [18]:
arr = np.array([1 , 2 , 3 , 4 , 5])
sq_arr = arr **2
sq_arr[sq_arr>10] = -1
#Normalisation
mean = np.mean(sq_arr)
std = np.std(sq_arr)
normalized_arr = (sq_arr-mean)/std
print(normalized_arr)

[-0.37099926  0.42399915  1.7489965  -0.9009982  -0.9009982 ]
