In [2]:
import numpy as np

In [3]:
#1
arr1 = np.zeros(10 , )
arr2 = np.ones((3 ,3))
arr3 = np.identity(4)
arr4 = np.arange(1 ,100 , 2)
arr5 = np.random.rand( 5 , 5 )
print(arr5.shape)
print(arr5.size)
print(arr5.dtype)
print(arr5.ndim)




(5, 5)
25
float64
2


In [4]:
#Indexing and Slicing
idx1 = [0 , 1 , 2 , 3 , 4]
idx2 = [-1 , -2 , -3 , -4 , -5]
print(arr4[idx1])
print(arr4[idx2])
rev_arr = arr4[-1::-1]
print(rev_arr)


[1 3 5 7 9]
[99 97 95 93 91]
[99 97 95 93 91 89 87 85 83 81 79 77 75 73 71 69 67 65 63 61 59 57 55 53
 51 49 47 45 43 41 39 37 35 33 31 29 27 25 23 21 19 17 15 13 11  9  7  5
  3  1]


In [5]:
#Creation Of A Numpy Array Filled With 10 zeroes
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#Creation Of a numpy array filled with ones
arr2 = np.ones((3 ,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
#Create a 1D NumPy array containing numbers from 1 to 20 (inclusive).
arr3 = np.arange(1 , 21)
print(arr3)
print(arr3.shape)
print(arr3.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
int64


In [12]:
#Extract the first 5 elements from arr3 (the array from 1 to 20).
sliced_arr = arr3[0:5]
print(sliced_arr)


[1 2 3 4 5]


In [13]:
#Extract the last 5 elements from arr3.
idx = [-1 , -2 , -3 , -4 , -5]
print(arr3[idx])

[20 19 18 17 16]


In [14]:
#Reversing The Array 3
reversed_arr = arr3[-1::-1]
print(reversed_arr)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [15]:
arr3[5:10] = -1
print(arr3)

[ 1  2  3  4  5 -1 -1 -1 -1 -1 11 12 13 14 15 16 17 18 19 20]


In [17]:
#Create a random 1D NumPy array of size 15 with integers between 1 and 100 (inclusive).
arr_random = np.random.randint(1 , 101 , size = (15 ,))
print(arr_random)

[50 84 35 59  4 63 29 43  6 84 35 82 36 23 37]


In [20]:
mean_random = np.mean(arr_random)#Caluculating Mean Of The Random Array
print(mean_random)

44.666666666666664


In [22]:
#Extracting Values That Are Greater Than Mean
mask = arr_random[arr_random>mean_random]
print(mask)



[50 84 59 63 84 82]


In [25]:
#counting vals less than 50
mask2 = [arr_random < 50]
count1 = np.sum(mask2)
print(count)


248
