In [1]:
import numpy as np

In [2]:
#🔹 Problem 1: Create a random 4×4 NumPy array
arr = np.random.randint(1 , 101 , size = (4 ,4))
print(arr)

[[67 65 44 96]
 [26  8 38  1]
 [18 84 55 53]
 [30 93 24 29]]


In [3]:
#Task:Extract First Row 
first_row = arr[0]
print(first_row)

[67 65 44 96]


In [5]:
#Extracting Last Col
last_col = arr[:,-1]
print(last_col)

[96  1 53 29]


In [7]:
center = arr[1:3 , 1:3]#Slicing The Center Part As (2,2) matrix
print(center)

[[ 8 38]
 [84 55]]


In [8]:
#Replace 2nd row with zeros
arr[1] = 0 
print(arr)

[[67 65 44 96]
 [ 0  0  0  0]
 [18 84 55 53]
 [30 93 24 29]]


In [9]:
#Mean Of Each Row
mean_row= np.mean(arr , axis = 1)
print(mean_row)

[68.   0.  52.5 44. ]


In [10]:
#Coloumn Wise Sum
col_sum = np.sum(arr , axis = 0)
print(col_sum)

[115 242 123 178]


In [12]:
#max value present in array
max_val = np.max(arr)
print(max_val)

96


In [13]:
#Min Value In An Array
min_val = np.min(arr)
print(min_val)

0


In [18]:
mask = arr>60#Vals Greater Than 60-->Count
count = np.sum(mask)
print(count)

5


In [17]:
mask = arr[arr>60]#Values In Array That Are Greater Than 60
print(mask)

[67 65 96 84 93]


In [20]:
arr[arr < 30] = 30#Replace Vals Which Are Less Than 30 with 30
print(arr)

[[67 65 44 96]
 [30 30 30 30]
 [30 84 55 53]
 [30 93 30 30]]


In [23]:
#Flattenment Of The Array
flattened_arr = arr.flatten()
print(flattened_arr)

[67 65 44 96 30 30 30 30 30 84 55 53 30 93 30 30]


In [26]:
sort_arr = np.sort(flattened_arr)#Sorting
print(sort_arr)

[30 30 30 30 30 30 30 30 44 53 55 65 67 84 93 96]
