In [1]:
import numpy as np


In [12]:
np.random.seed(42)
arr = np.random.randint(-50 , 51 , size = (5 , 3))
print(arr)

[[  1  42 -36]
 [ 21  10 -30]
 [ 32  36  24]
 [ 24  37  49]
 [-27 -48 -29]]


In [13]:
col_mean = np.mean(arr , axis = 0)
print(col_mean)
print(col_mean.shape)

[10.2 15.4 -4.4]
(3,)


In [14]:
centered_arr = arr-col_mean
print(centered_arr)
print(centered_arr.shape)

[[ -9.2  26.6 -31.6]
 [ 10.8  -5.4 -25.6]
 [ 21.8  20.6  28.4]
 [ 13.8  21.6  53.4]
 [-37.2 -63.4 -24.6]]
(5, 3)


In [10]:
mask = arr>0
positive_count = np.sum(mask)
print(positive_count)

10


In [11]:
mask = arr < 0
negative_count = np.sum(mask)
print(negative_count)

5


In [15]:
arr[arr < 0] = 0
print(arr)

[[ 1 42  0]
 [21 10  0]
 [32 36 24]
 [24 37 49]
 [ 0  0  0]]


In [17]:
scaled_arr = arr*2#Multiplication By A Scalar
print(scaled_arr)

[[  4 168   0]
 [ 84  40   0]
 [128 144  96]
 [ 96 148 196]
 [  0   0   0]]


In [21]:
add_arr = np.array([10 , 20 , 30])
broadcasted_arr  = scaled_arr+add_arr
print(broadcasted_arr)


[[ 14 188  30]
 [ 94  60  30]
 [138 164 126]
 [106 168 226]
 [ 10  20  30]]


In [23]:
#Z-score-Normalisation
mean_bc = np.mean(broadcasted_arr)
dev_bc = np.std(broadcasted_arr)
normalized_arr = (broadcasted_arr - mean_bc)/dev_bc
print(normalized_arr)

[[-1.14802173  1.36147301 -0.91726359]
 [ 0.00576895 -0.48459209 -0.91726359]
 [ 0.64035383  1.0153358   0.46728523]
 [ 0.17883756  1.07302534  1.90952358]
 [-1.20571127 -1.06148743 -0.91726359]]


In [26]:
min_arr = np.min(broadcasted_arr)
max_arr = np.max(broadcasted_arr)
normalized_arr = (broadcasted_arr-min_arr)/(max_arr - min_arr)
print(normalized_arr)

[[0.01851852 0.82407407 0.09259259]
 [0.38888889 0.23148148 0.09259259]
 [0.59259259 0.71296296 0.53703704]
 [0.44444444 0.73148148 1.        ]
 [0.         0.0462963  0.09259259]]


In [27]:
max_narr = np.max(normalized_arr)
print(max_narr)

1.0


In [29]:
min_narr = np.min(normalized_arr)
print(min_narr)

0.0


In [32]:
print(arr.shape)
print(col_mean.shape)
print(normalized_arr.shape)

(5, 3)
(3,)
(5, 3)


In [ ]:
#Practice on 11/2-->Ends