In [1]:
import numpy as np


In [2]:
arr = np.arange(1 , 25)
print(arr)
print(arr.shape)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)
int64


In [4]:
reshaped_array = arr.reshape((4 , 6))
print(reshaped_array)
print(reshaped_array.shape)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)


In [5]:
#Reshaping A 2D Array Into 3D Array With 2 Layers
r_2 = reshaped_array.reshape((2 , 3 , 4))
print(r_2)
print(r_2.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)


In [8]:
flattened = r_2.flatten()
print(flattened)
print(flattened.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)


In [10]:
row_max = np.max(reshaped_array , axis = 1)
print(row_max)

[ 6 12 18 24]


In [13]:
col_min = np.min(reshaped_array , axis = 0)
print(col_min)

[1 2 3 4 5 6]


In [14]:
sorted_arr = np.sort(reshaped_array)
print(sorted_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [15]:
sort_col = np.sort(reshaped_array , axis = 0)
print(sort_col)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [16]:
arr1 = np.array([40, 10, 30, 20])
sort_arg = np.argsort(arr1)#This Particular function in numpy returns the indices that makes an array sorted
print(sort_arg)
print(arr1[sort_arg])#This Is The Sorted Arr

[1 3 2 0]
[10 20 30 40]


In [18]:
max_index = np.argmax(arr)
print(max_index)

23


In [19]:
min_index= np.argmin(arr)
print(min_index)

0


In [21]:
arr[arr>20] = -1
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 -1 -1 -1 -1]
(24,)
