In [1]:
import numpy as np

In [3]:
np.random.seed(42)
arr = np.random.randint(1 , 101 , size = (6,4))
print(arr)

[[ 52  93  15  72]
 [ 61  21  83  87]
 [ 75  75  88 100]
 [ 24   3  22  53]
 [  2  88  30  38]
 [  2  64  60  21]]


In [4]:
col_mean = np.mean(arr ,  axis = 0)
print(col_mean)

[36.         57.33333333 49.66666667 61.83333333]


In [5]:
new_arr = arr - col_mean
print(new_arr)

[[ 16.          35.66666667 -34.66666667  10.16666667]
 [ 25.         -36.33333333  33.33333333  25.16666667]
 [ 39.          17.66666667  38.33333333  38.16666667]
 [-12.         -54.33333333 -27.66666667  -8.83333333]
 [-34.          30.66666667 -19.66666667 -23.83333333]
 [-34.           6.66666667  10.33333333 -40.83333333]]


In [6]:
row_sum = np.sum(arr ,  axis = 1)
print(row_sum)

[232 252 338 102 158 147]


In [7]:
row_average = np.mean(arr , axis = 1)
print(row_average)

[232 252 338 102 158 147]


In [9]:
mask = arr > 70
print(mask)

[[False  True False  True]
 [False False  True  True]
 [ True  True  True  True]
 [False False False False]
 [False  True False False]
 [False False False False]]


In [10]:
count = np.sum(mask)
print(count)

9


In [13]:
avg_arr = np.mean(arr)
arr[mask] = avg_arr
print(arr)

[[52 38 15 38]
 [61 21 38 38]
 [38 38 38 38]
 [24  3 22 53]
 [ 2 38 30 38]
 [ 2 64 60 21]]


In [15]:
flattened = arr.flatten()
print(flattened)

[52 38 15 38 61 21 38 38 38 38 38 38 24  3 22 53  2 38 30 38  2 64 60 21]


In [25]:
sort_fla = np.argsort(flattened)
descending = sort_fla[-1::-1]
print(flattened[descending])


[64 61 60 53 52 38 38 38 38 38 38 38 38 38 38 30 24 22 21 21 15  3  2  2]


In [26]:
f_2 = np.sort(flattened)
print(f_2[-1::-1])

[64 61 60 53 52 38 38 38 38 38 38 38 38 38 38 30 24 22 21 21 15  3  2  2]


In [35]:
descending = np.sort(flattened)[::-1]

top5 = descending[:5]
print(top5)
bot5 = descending[-5:]
print(bot5)


[64 61 60 53 52]
[21 15  3  2  2]


In [37]:
unq = np.unique(f_2)
print(unq)

[ 2  3 15 21 22 24 30 38 52 53 60 61 64]
