In [1]:
import numpy as np

In [5]:
np.random.seed(42)#For Reproducability
arr = np.random.randint(10 , 101 , size = (10 , 5))
print(arr)
print(arr.shape)


[[ 61  24  81  70  30]
 [ 92  96  84  84  97]
 [ 33  12  31  62  11]
 [ 97  39  47  11  73]
 [ 69  30  42  85  67]
 [ 31  98  58 100  68]
 [ 51  69  89  24  71]
 [ 71  56  71  60  64]
 [ 73  12  60  16  30]
 [ 82  48  27  13  98]]
(10, 5)


In [7]:
converted = arr.astype(dtype = 'float64')
print(converted.dtype)

float64


In [15]:
import numpy as np

# Assuming converted is already created
converted[2, 3] = np.nan
converted[7, 1] = np.nan
converted[5, 4] = np.nan

print(converted)

# Count total NaNs
print("Total NaNs:", np.isnan(converted).sum())


[[61. 24. 81. 70. 30.]
 [92. 96. 84. 84. 97.]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]
Total NaNs: 40


In [23]:
col_mean = np.nanmean(converted , axis = 0)
print(col_mean)
mask = converted[2: , :]
mask = col_mean
print(mask)

[76.5 60.  82.5 77.  63.5]
[76.5 60.  82.5 77.  63.5]
